.TH DOXYPARSE "1" "DATE" "doxyparse VERSION" "User Commands"
.SH NAME
doxyparse \- parse and dumps information about the code
.SH SYNOPSIS
.B doxyparse
[\fIsource file\fR...]
.SH DESCRIPTION
Parses source code and dumps the dependencies between the code elements.
.SH SEE ALSO
doxygen(1), doxytag(1), doxywizard(1).
