# name (and path if needed) of the make tool to use
# note that make must really be GNU make, not BSD or some other make
MAKE    = make  

# name (and path if needed) of the perl interpreter
# note that it must be version 5 or higher (check with perl -v)
PERL    = perl  

# The values below should probably be left unmodified
TAR     = tar   # name of the GNU tar tool
TMAKE   = ../tmake/bin/tmake
VERSION = 0.49-990425
