#############################################################################
#!
#! This is a tmake template for creating a makefile that invokes make in
#! sub directories - for Win32/Borland C++.
#!
#${
    StdInit();
    $m = "";
    foreach ( split(/\s+/,$project{"SUBDIRS"}) ) {
	$m = $m . "\tcd $_\n\tDOMAKE\n\t\@cd ..\n";
    }
    $project{"SUBMAKE"} = $m;
#$}
#!
# Makefile for building targets in sub directories.
# Generated by tmake at #$ Now();
#     Project: #$ Expand("PROJECT");
#    Template: #$ Expand("TEMPLATE");
#############################################################################

SUBDIRS =	#$ ExpandList("SUBDIRS");

all: $(SUBDIRS)

#${
    foreach ( split(/\s+/,$project{"SUBDIRS"}) ) {
	$text = $text . $_ . ":\n\t" .
		"cd $_\n\t\$(MAKE\)\n\t\@cd ..\n\n";
    }
#$}

clean:
#$ $text = $project{"SUBMAKE"}; $text =~ s/DOMAKE/\$(MAKE\) clean/g;
