.TH DOXYWIZARD "1" "@DATE@" "doxywizard @VERSION@" "User Commands"
.SH NAME
Doxywizard \- a tool to configure and run Doxygen on your source files
.SH SYNOPSIS
.B doxywizard
.RI [Doxyfile]
.SH DESCRIPTION
Doxywizard is an interactive frontend to the Doxygen tool to configure
and run Doxygen on your source files.
.SH SEE ALSO
doxygen(1)
