.TH DOXYSEARCH "1" "@DATE@" "doxysearch.cgi @VERSION@" "User Commands"
.SH NAME
doxysearch.cgi \- search engine for Doxygen documentation
.SH SYNOPSIS
.B doxysearch.cgi
.SH DESCRIPTION
CGI binary used by Doxygen-generated HTML output to search for words.
The tool uses the search index \fBdoxysearch.db\fR produced by doxyindexer.
.SH SEE ALSO
doxygen(1), doxyindexer(1), doxywizard(1).
