.TH DOXYWIZARD "1" "DATE" "doxywizard VERSION" "User Commands"
.SH NAME
doxywizard \- a tool to configure and run doxygen on your source files
.SH SYNOPSIS
.B doxywizard
.SH DESCRIPTION
Doxywizard is an interactive frontend to the doxygen tool to configure
and run doxygen on your source files.
.PP
You can optionally pass the name of a configuration file as the first argument
to load it at startup.
.SH SEE ALSO
doxygen(1)
