059_command_catch.tcl
Invokedargs
should be reference by every proc below
Referenced by a, b, c, d, e, f, g, h, i, j.
NotInvokedargs
must not be reference by every proc below
aargs
References Invoked.
bargs
References Invoked.
cargs
References Invoked.
dargs
References Invoked.
eargs
References Invoked.
fargs
References Invoked.
gargs
References Invoked.
hargs
References Invoked.
iargs
References Invoked.
jargs
References Invoked.