"<xsd:schema xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n"
"  <xsd:element name=\"doxygen\" type=\"DoxygenType\"/>\n"
"\n"
"  <xsd:complexType name=\"DoxygenType\">\n"
"    <xsd:sequence>\n"
"    </xsd:sequence>\n"
"    <xsd:attribute name=\"version\" type=\"xsd:string\" use=\"required\"/>\n"
"  </xsd:complexType>\n"
"\n"
"</xsd:schema>\n"
"\n"
