"function toggleVisibility(linkObj)\n"
"{\n"
" var base = $(linkObj).attr('id');\n"
" var summary = $('#'+base+'-summary');\n"
" var content = $('#'+base+'-content');\n"
" var trigger = $('#'+base+'-trigger');\n"
" var src=$(trigger).attr('src');\n"
" if (content.is(':visible')===true) {\n"
"   content.hide();\n"
"   summary.show();\n"
"   $(linkObj).addClass('closed').removeClass('opened');\n"
"   $(trigger).attr('src',src.substring(0,src.length-8)+'closed.png');\n"
" } else {\n"
"   content.show();\n"
"   summary.hide();\n"
"   $(linkObj).removeClass('closed').addClass('opened');\n"
"   $(trigger).attr('src',src.substring(0,src.length-10)+'open.png');\n"
" } \n"
" return false;\n"
"}\n"
"\n"
"function updateStripes()\n"
"{\n"
"  $('table.directory tr').\n"
"       removeClass('even').filter(':visible:even').addClass('even');\n"
"}\n"
"function toggleLevel(level)\n"
"{\n"
"  $('table.directory tr').each(function(){ \n"
"    var l = this.id.split('_').length-1;\n"
"    var i = $('#img'+this.id.substring(3));\n"
"    var a = $('#arr'+this.id.substring(3));\n"
"    if (l<level+1) {\n"
"      i.attr('src','ftv2folderopen.png');\n"
"      a.attr('src','ftv2mnode.png');\n"
"      $(this).show();\n"
"    } else if (l==level+1) {\n"
"      i.attr('src','ftv2folderclosed.png');\n"
"      a.attr('src','ftv2pnode.png');\n"
"      $(this).show();\n"
"    } else {\n"
"      $(this).hide();\n"
"    }\n"
"  });\n"
"  updateStripes();\n"
"}\n"
"function toggleFolder(id) \n"
"{\n"
"  var n = $('[id^=row_'+id+']');\n"
"  var i = $('[id^=img_'+id+']');\n"
"  var a = $('[id^=arr_'+id+']');\n"
"  var c = n.slice(1);\n"
"  if (c.filter(':first').is(':visible')===true) {\n"
"    i.attr('src','ftv2folderclosed.png');\n"
"    a.attr('src','ftv2pnode.png');\n"
"    c.hide();\n"
"  } else {\n"
"    i.attr('src','ftv2folderopen.png');\n"
"    a.attr('src','ftv2mnode.png');\n"
"    c.show();\n"
"  }\n"
"  updateStripes();\n"
"}\n"
"\n"
"function toggleInherit(id)\n"
"{\n"
"  var rows = $('tr.inherit.'+id);\n"
"  var img = $('tr.inherit_header.'+id+' img');\n"
"  var src = $(img).attr('src');\n"
"  if (rows.filter(':first').is(':visible')===true) {\n"
"    rows.css('display','none');\n"
"    $(img).attr('src',src.substring(0,src.length-8)+'closed.png');\n"
"  } else {\n"
"    rows.css('display','table-row'); // using show() causes jump in firefox\n"
"    $(img).attr('src',src.substring(0,src.length-10)+'open.png');\n"
"  }\n"
"}\n"
"\n"
