#define LANG_NL
#define LANG_SE
#define LANG_CZ
#define LANG_FR
#define LANG_IT
#define LANG_DE
#define LANG_JP
#define LANG_ES
#define LANG_FI
#define LANG_RU
#define LANG_HR
#define LANG_PL
#define LANG_PT
#define LANG_HU
#define LANG_KR
#define LANG_RO
#define LANG_SI
#define LANG_CN
#define LANG_NO
#define LANG_BR
#define LANG_DK
#define LANG_SK
#define LANG_UA
#define LANG_GR
#define LANG_TW
#define LANG_SR
#define LANG_CA
