"#nav-tree .children_ul {\n"
"  margin:0;\n"
"  padding:4px;\n"
"}\n"
"\n"
"#nav-tree ul {\n"
"  list-style:none outside none;\n"
"  margin:0px;\n"
"  padding:0px;\n"
"}\n"
"\n"
"#nav-tree li {\n"
"  white-space:nowrap;\n"
"  margin:0px;\n"
"  padding:0px;\n"
"}\n"
"\n"
"#nav-tree .plus {\n"
"  margin:0px;\n"
"}\n"
"\n"
"#nav-tree .selected {\n"
"  background-image: url('tab_a.png');\n"
"  background-repeat:repeat-x;\n"
"  color: #fff;\n"
"  text-shadow: 0px 1px 1px rgba(0, 0, 0, 1.0);\n"
"}\n"
"\n"
"#nav-tree img {\n"
"  margin:0px;\n"
"  padding:0px;\n"
"  border:0px;\n"
"  vertical-align: middle;\n"
"}\n"
"\n"
"#nav-tree a {\n"
"  text-decoration:none;\n"
"  padding:0px;\n"
"  margin:0px;\n"
"  outline:none;\n"
"}\n"
"\n"
"#nav-tree .label {\n"
"  margin:0px;\n"
"  padding:0px;\n"
"}\n"
"\n"
"#nav-tree .label a {\n"
"  padding:2px;\n"
"}\n"
"\n"
"#nav-tree .selected a {\n"
"  text-decoration:none;\n"
"  padding:2px;\n"
"  margin:0px;\n"
"  color:#fff;\n"
"}\n"
"\n"
"#nav-tree .children_ul {\n"
"  margin:0px;\n"
"  padding:0px;\n"
"}\n"
"\n"
"#nav-tree .item {\n"
"  margin:0px;\n"
"  padding:0px;\n"
"}\n"
"\n"
"#nav-tree {\n"
"  padding: 0px 0px;\n"
"  background-color: #FAFAFF; \n"
"  font-size:14px;\n"
"  overflow:auto;\n"
"}\n"
"\n"
"#doc-content {\n"
"  overflow:auto;\n"
"  display:block;\n"
"  padding:0px;\n"
"  margin:0px;\n"
"}\n"
"\n"
"#side-nav {\n"
"  padding:0 6px 0 0;\n"
"  margin: 0px;\n"
"  display:block;\n"
"  position: absolute;\n"
"  left: 0px;\n"
"  width: 300px;\n"
"}\n"
"\n"
".ui-resizable .ui-resizable-handle {\n"
"  display:block;\n"
"}\n"
"\n"
".ui-resizable-e {\n"
"  background:url(\"ftv2splitbar.png\") repeat scroll right center transparent;\n"
"  cursor:e-resize;\n"
"  height:100%;\n"
"  right:0;\n"
"  top:0;\n"
"  width:6px;\n"
"}\n"
"\n"
".ui-resizable-handle {\n"
"  display:none;\n"
"  font-size:0.1px;\n"
"  position:absolute;\n"
"  z-index:1;\n"
"}\n"
"\n"
"#nav-tree-contents {\n"
"  margin: 6px 0px 0px 0px;\n"
"}\n"
"\n"
"#nav-tree {\n"
"  background-image:url('nav_h.png');\n"
"  background-repeat:repeat-x;\n"
"  background-color: ##FA;\n"
"}\n"
"\n"
"\n"
"\n"
