if(${CMAKE_ARGC} GREATER 2)
	if ("${CMAKE_ARGV4}" STREQUAL "ENONLY")
		file(APPEND ${CMAKE_ARGV3} " #define ENGLISH_ONLY\n")
	else()
		math(EXPR UPTO ${CMAKE_ARGC}-1)
		foreach(i RANGE 4 ${UPTO})
			file(APPEND ${CMAKE_ARGV3} " #define LANG_${CMAKE_ARGV${i}}\n")
		endforeach()
	endif()
endif()

