file (STRINGS "VERSION" VERSION)
#string(REGEX MATCH "([0-9]+).([0-9]+).([0-9]+)" ${doxygen_version_major} ${doxygen_version_minor} ${doxygen_version_revision} )
#set(doxygen_version_major    "1" CACHE STRING "Major")
#set(doxygen_version_minor    "8" CACHE STRING "Minor")
#set(doxygen_version_revision "9.1" CACHE STRING "Revision")
#set(doxygen_version_mmn      "-5" CACHE STRING "Mmn")
#set(VERSION "${doxygen_version_major}.${doxygen_version_minor}.${doxygen_version_revision}${doxygen_version_mmn}")
set(ENV{VERSION} "${VERSION}")
