# ----------------------------------------------------------
# project: doxygen
# autor:   Dimitri van Heesch
#
# desc:    this workflow provides some translations for the
#          doxygen project.
#          The files that are created by this workflow file
#          can be used platform independed, so no need for
#          more workflows for translations.
# ----------------------------------------------------------
name: Build Locales for Doxygen

on:
  push:
    branches:
      - private
  pull_request:
    branches:
      - private

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install gettext
      run: sudo apt-get install -y gettext

    - name: Compile Translations (English)
      run: |
        mkdir -p locale/en/LC_MESSAGES
        msgfmt -o locale/en/LC_MESSAGES/messages.mo locale/en.po
        mkdir -p bin/locale/en/LC_MESSAGES
        cp locale/en/LC_MESSAGES/messages.po bin/locale/en/LC_MESSAGES/messages.po
    
    - name: Compile Translations (German)
      run: |
        mkdir -p locale/de/LC_MESSAGES
        msgfmt -o locale/de/LC_MESSAGES/messages.mo locale/de.po
        mkdir -p bin/locale/de/LC_MESSAGES
        cp locale/de/LC_MESSAGES/messages.po bin/locale/de/LC_MESSAGES/messages.po
        
    - name: Create Archive
      run: |
        mkdir -p build_artifacts
        cp -r locale build_artifacts/
        tar -czvf build_artifacts/translations.tar.gz locale/
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-translations
        path: build_artifacts/
        
    #- name: Build C++ Application
    #  run: g++ main.cpp -o app -lintl

    #- name: Test Application (German)
    #  run: LANG=de_DE ./app
